name: Generate GitHub Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: ahmadsaif12
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake-white.svg?color_snake=white&color_dots=#161b22,#0e4429,#006d32,#26a641,#39d353

      - name: Push to output branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan output
          git rm -rf .
          mv dist/* . 2>/dev/null || true
          git add .
          git commit -m "Update contribution snake" --allow-empty
          git push origin output --force
